version: '3.5'

x-volumes: &site-volumes
  volumes:
    - ./drupal:/var/www/site
    - ./drupal-files:/var/www/site/web/sites/default
    - ./docker/nginx:/etc/nginx/conf.d

services:
  webserver:
    <<: *site-volumes
    image: nginx:1.17.4-alpine
    container_name: drupal_nginx
    restart: always
    networks:
      drupal_net:
        aliases:
          - 10.drupal.docker
    depends_on:
      - drupal-php
    environment:
      - VIRTUAL_HOST=10.drupal.docker
    ports:
     - "127.0.0.1:80:80"

  # composer create-project --no-interaction "drupal/recommended-project:$DRUPAL_VERSION" ./; \
  drupal-php:
    <<: *site-volumes
    build: docker/drupal-php
    container_name: drupal_php
    restart: always
    networks:
      - drupal_net
#    environment:
#      PATH: "/var/www/site/vendor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    env_file:
      - .env
    working_dir: /var/www/site/web
    command: sh -c 'chown -R www-data.www-data /var/www/site/web/sites/default && php-fpm'

  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - drupal-10-mysql:/var/lib/mysql
    networks:
      - drupal_net

volumes:
  drupal-10-mysql:

networks:
  drupal_net:
    driver: bridge
    name: drupal_net
